name: Sync packages
on: 
    workflow_dispatch:
    schedule:
        - cron: "*/5 * * * *"
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 22
        uses: actions/setup-node@v4
        with:
            node-version: 22
      - name: Install Yarn
        run: npm install --global yarn
      - name: Yarn install
        run: yarn install --pure-lockfile --non-interactive
      - name: Update package.json and yarn.lock
        run: yarn run start
      - name: Yarn cache clean
        run: yarn cache clean
      - name: Sanity check
        run: yarn install --frozen-lockfile --non-interactive
      - name: Commit files
        run: |
          git config --global user.name 'Jacob Kerr'
          git config --global user.email 'jakejack13@users.noreply.github.com'
          git commit -am "Sync packages"
          git push
